import Head from "next/head";
import { Fragment } from "react";
import Navbar from "../navbar/navbar";

export default function Layout({ children, title }) {
  return (
    <Fragment>
      <Head>
        <title>Daily App | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="flex flex-col px-10">{children}</div>
      </main>
      <footer></footer>
    </Fragment>
  );
}
